version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "php"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/BlackTriumph993/http4k-webgoat"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"